/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AccountId = bigint;
export type AccountType = { 'Savings' : null } |
  { 'Checking' : null };
export interface AccountView {
  'balance' : bigint,
  'accountId' : AccountId,
  'ownerId' : UserId,
  'createdAt' : Timestamp,
  'accountType' : AccountType,
  'accountNumber' : string,
}
export type NotificationId = bigint;
export type NotificationType = { 'TransferConfirmation' : null } |
  { 'LoginAlert' : null } |
  { 'AccountActivity' : null } |
  { 'SecurityAlert' : null };
export interface NotificationView {
  'title' : string,
  'notifType' : NotificationType,
  'userId' : UserId,
  'notifId' : NotificationId,
  'isRead' : boolean,
  'message' : string,
  'timestamp' : Timestamp,
}
export type Timestamp = bigint;
export interface Transaction {
  'status' : TransactionStatus,
  'referenceNumber' : string,
  'fromAccount' : [] | [AccountId],
  'txId' : TransactionId,
  'description' : string,
  'timestamp' : Timestamp,
  'category' : TransactionCategory,
  'toAccount' : [] | [AccountId],
  'amount' : bigint,
}
export type TransactionCategory = { 'Deposit' : null } |
  { 'Withdrawal' : null } |
  { 'Transfer' : null } |
  { 'Payment' : null };
export type TransactionId = bigint;
export interface TransactionPage {
  'total' : bigint,
  'hasMore' : boolean,
  'transactions' : Array<Transaction>,
}
export type TransactionStatus = { 'Failed' : null } |
  { 'Completed' : null } |
  { 'Pending' : null };
export interface TransferRequest {
  'description' : string,
  'toAccountId' : AccountId,
  'fromAccountId' : AccountId,
  'amount' : bigint,
}
export interface TransferResult {
  'transaction' : Transaction,
  'newFromBalance' : bigint,
  'newToBalance' : bigint,
}
export type UserId = Principal;
export interface _SERVICE {
  'createAccount' : ActorMethod<[AccountType], AccountView>,
  'dismissNotification' : ActorMethod<[NotificationId], boolean>,
  'getAccount' : ActorMethod<[AccountId], [] | [AccountView]>,
  'getMyAccounts' : ActorMethod<[], Array<AccountView>>,
  'getNotifications' : ActorMethod<[], Array<NotificationView>>,
  'getTransaction' : ActorMethod<[TransactionId], [] | [Transaction]>,
  'getTransactions' : ActorMethod<[AccountId, bigint, bigint], TransactionPage>,
  'getUnreadCount' : ActorMethod<[], bigint>,
  'initSampleData' : ActorMethod<[], boolean>,
  'isSampleDataSeeded' : ActorMethod<[], boolean>,
  'markNotificationRead' : ActorMethod<[NotificationId], boolean>,
  'transfer' : ActorMethod<[TransferRequest], TransferResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];