/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AccountType = IDL.Variant({
  'Savings' : IDL.Null,
  'Checking' : IDL.Null,
});
export const AccountId = IDL.Nat;
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const AccountView = IDL.Record({
  'balance' : IDL.Nat,
  'accountId' : AccountId,
  'ownerId' : UserId,
  'createdAt' : Timestamp,
  'accountType' : AccountType,
  'accountNumber' : IDL.Text,
});
export const NotificationId = IDL.Nat;
export const NotificationType = IDL.Variant({
  'TransferConfirmation' : IDL.Null,
  'LoginAlert' : IDL.Null,
  'AccountActivity' : IDL.Null,
  'SecurityAlert' : IDL.Null,
});
export const NotificationView = IDL.Record({
  'title' : IDL.Text,
  'notifType' : NotificationType,
  'userId' : UserId,
  'notifId' : NotificationId,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
  'timestamp' : Timestamp,
});
export const TransactionId = IDL.Nat;
export const TransactionStatus = IDL.Variant({
  'Failed' : IDL.Null,
  'Completed' : IDL.Null,
  'Pending' : IDL.Null,
});
export const TransactionCategory = IDL.Variant({
  'Deposit' : IDL.Null,
  'Withdrawal' : IDL.Null,
  'Transfer' : IDL.Null,
  'Payment' : IDL.Null,
});
export const Transaction = IDL.Record({
  'status' : TransactionStatus,
  'referenceNumber' : IDL.Text,
  'fromAccount' : IDL.Opt(AccountId),
  'txId' : TransactionId,
  'description' : IDL.Text,
  'timestamp' : Timestamp,
  'category' : TransactionCategory,
  'toAccount' : IDL.Opt(AccountId),
  'amount' : IDL.Nat,
});
export const TransactionPage = IDL.Record({
  'total' : IDL.Nat,
  'hasMore' : IDL.Bool,
  'transactions' : IDL.Vec(Transaction),
});
export const TransferRequest = IDL.Record({
  'description' : IDL.Text,
  'toAccountId' : AccountId,
  'fromAccountId' : AccountId,
  'amount' : IDL.Nat,
});
export const TransferResult = IDL.Record({
  'transaction' : Transaction,
  'newFromBalance' : IDL.Nat,
  'newToBalance' : IDL.Nat,
});

export const idlService = IDL.Service({
  'createAccount' : IDL.Func([AccountType], [AccountView], []),
  'dismissNotification' : IDL.Func([NotificationId], [IDL.Bool], []),
  'getAccount' : IDL.Func([AccountId], [IDL.Opt(AccountView)], ['query']),
  'getMyAccounts' : IDL.Func([], [IDL.Vec(AccountView)], ['query']),
  'getNotifications' : IDL.Func([], [IDL.Vec(NotificationView)], ['query']),
  'getTransaction' : IDL.Func(
      [TransactionId],
      [IDL.Opt(Transaction)],
      ['query'],
    ),
  'getTransactions' : IDL.Func(
      [AccountId, IDL.Nat, IDL.Nat],
      [TransactionPage],
      ['query'],
    ),
  'getUnreadCount' : IDL.Func([], [IDL.Nat], ['query']),
  'initSampleData' : IDL.Func([], [IDL.Bool], []),
  'isSampleDataSeeded' : IDL.Func([], [IDL.Bool], ['query']),
  'markNotificationRead' : IDL.Func([NotificationId], [IDL.Bool], []),
  'transfer' : IDL.Func([TransferRequest], [TransferResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AccountType = IDL.Variant({
    'Savings' : IDL.Null,
    'Checking' : IDL.Null,
  });
  const AccountId = IDL.Nat;
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const AccountView = IDL.Record({
    'balance' : IDL.Nat,
    'accountId' : AccountId,
    'ownerId' : UserId,
    'createdAt' : Timestamp,
    'accountType' : AccountType,
    'accountNumber' : IDL.Text,
  });
  const NotificationId = IDL.Nat;
  const NotificationType = IDL.Variant({
    'TransferConfirmation' : IDL.Null,
    'LoginAlert' : IDL.Null,
    'AccountActivity' : IDL.Null,
    'SecurityAlert' : IDL.Null,
  });
  const NotificationView = IDL.Record({
    'title' : IDL.Text,
    'notifType' : NotificationType,
    'userId' : UserId,
    'notifId' : NotificationId,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const TransactionId = IDL.Nat;
  const TransactionStatus = IDL.Variant({
    'Failed' : IDL.Null,
    'Completed' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const TransactionCategory = IDL.Variant({
    'Deposit' : IDL.Null,
    'Withdrawal' : IDL.Null,
    'Transfer' : IDL.Null,
    'Payment' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'status' : TransactionStatus,
    'referenceNumber' : IDL.Text,
    'fromAccount' : IDL.Opt(AccountId),
    'txId' : TransactionId,
    'description' : IDL.Text,
    'timestamp' : Timestamp,
    'category' : TransactionCategory,
    'toAccount' : IDL.Opt(AccountId),
    'amount' : IDL.Nat,
  });
  const TransactionPage = IDL.Record({
    'total' : IDL.Nat,
    'hasMore' : IDL.Bool,
    'transactions' : IDL.Vec(Transaction),
  });
  const TransferRequest = IDL.Record({
    'description' : IDL.Text,
    'toAccountId' : AccountId,
    'fromAccountId' : AccountId,
    'amount' : IDL.Nat,
  });
  const TransferResult = IDL.Record({
    'transaction' : Transaction,
    'newFromBalance' : IDL.Nat,
    'newToBalance' : IDL.Nat,
  });
  
  return IDL.Service({
    'createAccount' : IDL.Func([AccountType], [AccountView], []),
    'dismissNotification' : IDL.Func([NotificationId], [IDL.Bool], []),
    'getAccount' : IDL.Func([AccountId], [IDL.Opt(AccountView)], ['query']),
    'getMyAccounts' : IDL.Func([], [IDL.Vec(AccountView)], ['query']),
    'getNotifications' : IDL.Func([], [IDL.Vec(NotificationView)], ['query']),
    'getTransaction' : IDL.Func(
        [TransactionId],
        [IDL.Opt(Transaction)],
        ['query'],
      ),
    'getTransactions' : IDL.Func(
        [AccountId, IDL.Nat, IDL.Nat],
        [TransactionPage],
        ['query'],
      ),
    'getUnreadCount' : IDL.Func([], [IDL.Nat], ['query']),
    'initSampleData' : IDL.Func([], [IDL.Bool], []),
    'isSampleDataSeeded' : IDL.Func([], [IDL.Bool], ['query']),
    'markNotificationRead' : IDL.Func([NotificationId], [IDL.Bool], []),
    'transfer' : IDL.Func([TransferRequest], [TransferResult], []),
  });
};

export const init = ({ IDL }) => { return []; };