/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface TransferRequest {
    description: string;
    toAccountId: AccountId;
    fromAccountId: AccountId;
    amount: bigint;
}
export interface TransactionPage {
    total: bigint;
    hasMore: boolean;
    transactions: Array<Transaction>;
}
export interface AccountView {
    balance: bigint;
    accountId: AccountId;
    ownerId: UserId;
    createdAt: Timestamp;
    accountType: AccountType;
    accountNumber: string;
}
export interface NotificationView {
    title: string;
    notifType: NotificationType;
    userId: UserId;
    notifId: NotificationId;
    isRead: boolean;
    message: string;
    timestamp: Timestamp;
}
export type UserId = Principal;
export type TransactionId = bigint;
export interface Transaction {
    status: TransactionStatus;
    referenceNumber: string;
    fromAccount?: AccountId;
    txId: TransactionId;
    description: string;
    timestamp: Timestamp;
    category: TransactionCategory;
    toAccount?: AccountId;
    amount: bigint;
}
export interface TransferResult {
    transaction: Transaction;
    newFromBalance: bigint;
    newToBalance: bigint;
}
export type NotificationId = bigint;
export type AccountId = bigint;
export enum AccountType {
    Savings = "Savings",
    Checking = "Checking"
}
export enum NotificationType {
    TransferConfirmation = "TransferConfirmation",
    LoginAlert = "LoginAlert",
    AccountActivity = "AccountActivity",
    SecurityAlert = "SecurityAlert"
}
export enum TransactionCategory {
    Deposit = "Deposit",
    Withdrawal = "Withdrawal",
    Transfer = "Transfer",
    Payment = "Payment"
}
export enum TransactionStatus {
    Failed = "Failed",
    Completed = "Completed",
    Pending = "Pending"
}
export interface backendInterface {
    createAccount(accountType: AccountType): Promise<AccountView>;
    dismissNotification(notifId: NotificationId): Promise<boolean>;
    getAccount(accountId: AccountId): Promise<AccountView | null>;
    getMyAccounts(): Promise<Array<AccountView>>;
    getNotifications(): Promise<Array<NotificationView>>;
    getTransaction(txId: TransactionId): Promise<Transaction | null>;
    getTransactions(accountId: AccountId, offset: bigint, limit: bigint): Promise<TransactionPage>;
    getUnreadCount(): Promise<bigint>;
    initSampleData(): Promise<boolean>;
    isSampleDataSeeded(): Promise<boolean>;
    markNotificationRead(notifId: NotificationId): Promise<boolean>;
    transfer(req: TransferRequest): Promise<TransferResult>;
}
import type { AccountId as _AccountId, AccountType as _AccountType, AccountView as _AccountView, NotificationId as _NotificationId, NotificationType as _NotificationType, NotificationView as _NotificationView, Timestamp as _Timestamp, Transaction as _Transaction, TransactionCategory as _TransactionCategory, TransactionId as _TransactionId, TransactionPage as _TransactionPage, TransactionStatus as _TransactionStatus, TransferResult as _TransferResult, UserId as _UserId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createAccount(arg0: AccountType): Promise<AccountView> {
        if (this.processError) {
            try {
                const result = await this.actor.createAccount(to_candid_AccountType_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_AccountView_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAccount(to_candid_AccountType_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_AccountView_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async dismissNotification(arg0: NotificationId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.dismissNotification(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.dismissNotification(arg0);
            return result;
        }
    }
    async getAccount(arg0: AccountId): Promise<AccountView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAccount(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAccount(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyAccounts(): Promise<Array<AccountView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyAccounts();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyAccounts();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotifications(): Promise<Array<NotificationView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotifications();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotifications();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransaction(arg0: TransactionId): Promise<Transaction | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransaction(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransaction(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactions(arg0: AccountId, arg1: bigint, arg2: bigint): Promise<TransactionPage> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactions(arg0, arg1, arg2);
                return from_candid_TransactionPage_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactions(arg0, arg1, arg2);
            return from_candid_TransactionPage_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUnreadCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadCount();
            return result;
        }
    }
    async initSampleData(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.initSampleData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initSampleData();
            return result;
        }
    }
    async isSampleDataSeeded(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isSampleDataSeeded();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isSampleDataSeeded();
            return result;
        }
    }
    async markNotificationRead(arg0: NotificationId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationRead(arg0);
            return result;
        }
    }
    async transfer(arg0: TransferRequest): Promise<TransferResult> {
        if (this.processError) {
            try {
                const result = await this.actor.transfer(arg0);
                return from_candid_TransferResult_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transfer(arg0);
            return from_candid_TransferResult_n25(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AccountType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AccountType): AccountType {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_AccountView_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AccountView): AccountView {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationType): NotificationType {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationView_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationView): NotificationView {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionCategory_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionCategory): TransactionCategory {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionPage_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionPage): TransactionPage {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionStatus): TransactionStatus {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_TransferResult_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransferResult): TransferResult {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Transaction]): Transaction | null {
    return value.length === 0 ? null : from_candid_Transaction_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AccountId]): AccountId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AccountView]): AccountView | null {
    return value.length === 0 ? null : from_candid_AccountView_n3(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    notifType: _NotificationType;
    userId: _UserId;
    notifId: _NotificationId;
    isRead: boolean;
    message: string;
    timestamp: _Timestamp;
}): {
    title: string;
    notifType: NotificationType;
    userId: UserId;
    notifId: NotificationId;
    isRead: boolean;
    message: string;
    timestamp: Timestamp;
} {
    return {
        title: value.title,
        notifType: from_candid_NotificationType_n12(_uploadFile, _downloadFile, value.notifType),
        userId: value.userId,
        notifId: value.notifId,
        isRead: value.isRead,
        message: value.message,
        timestamp: value.timestamp
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _TransactionStatus;
    referenceNumber: string;
    fromAccount: [] | [_AccountId];
    txId: _TransactionId;
    description: string;
    timestamp: _Timestamp;
    category: _TransactionCategory;
    toAccount: [] | [_AccountId];
    amount: bigint;
}): {
    status: TransactionStatus;
    referenceNumber: string;
    fromAccount?: AccountId;
    txId: TransactionId;
    description: string;
    timestamp: Timestamp;
    category: TransactionCategory;
    toAccount?: AccountId;
    amount: bigint;
} {
    return {
        status: from_candid_TransactionStatus_n17(_uploadFile, _downloadFile, value.status),
        referenceNumber: value.referenceNumber,
        fromAccount: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.fromAccount)),
        txId: value.txId,
        description: value.description,
        timestamp: value.timestamp,
        category: from_candid_TransactionCategory_n20(_uploadFile, _downloadFile, value.category),
        toAccount: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.toAccount)),
        amount: value.amount
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    hasMore: boolean;
    transactions: Array<_Transaction>;
}): {
    total: bigint;
    hasMore: boolean;
    transactions: Array<Transaction>;
} {
    return {
        total: value.total,
        hasMore: value.hasMore,
        transactions: from_candid_vec_n24(_uploadFile, _downloadFile, value.transactions)
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    transaction: _Transaction;
    newFromBalance: bigint;
    newToBalance: bigint;
}): {
    transaction: Transaction;
    newFromBalance: bigint;
    newToBalance: bigint;
} {
    return {
        transaction: from_candid_Transaction_n15(_uploadFile, _downloadFile, value.transaction),
        newFromBalance: value.newFromBalance,
        newToBalance: value.newToBalance
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    balance: bigint;
    accountId: _AccountId;
    ownerId: _UserId;
    createdAt: _Timestamp;
    accountType: _AccountType;
    accountNumber: string;
}): {
    balance: bigint;
    accountId: AccountId;
    ownerId: UserId;
    createdAt: Timestamp;
    accountType: AccountType;
    accountNumber: string;
} {
    return {
        balance: value.balance,
        accountId: value.accountId,
        ownerId: value.ownerId,
        createdAt: value.createdAt,
        accountType: from_candid_AccountType_n5(_uploadFile, _downloadFile, value.accountType),
        accountNumber: value.accountNumber
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    TransferConfirmation: null;
} | {
    LoginAlert: null;
} | {
    AccountActivity: null;
} | {
    SecurityAlert: null;
}): NotificationType {
    return "TransferConfirmation" in value ? NotificationType.TransferConfirmation : "LoginAlert" in value ? NotificationType.LoginAlert : "AccountActivity" in value ? NotificationType.AccountActivity : "SecurityAlert" in value ? NotificationType.SecurityAlert : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Failed: null;
} | {
    Completed: null;
} | {
    Pending: null;
}): TransactionStatus {
    return "Failed" in value ? TransactionStatus.Failed : "Completed" in value ? TransactionStatus.Completed : "Pending" in value ? TransactionStatus.Pending : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Deposit: null;
} | {
    Withdrawal: null;
} | {
    Transfer: null;
} | {
    Payment: null;
}): TransactionCategory {
    return "Deposit" in value ? TransactionCategory.Deposit : "Withdrawal" in value ? TransactionCategory.Withdrawal : "Transfer" in value ? TransactionCategory.Transfer : "Payment" in value ? TransactionCategory.Payment : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Savings: null;
} | {
    Checking: null;
}): AccountType {
    return "Savings" in value ? AccountType.Savings : "Checking" in value ? AccountType.Checking : value;
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AccountView>): Array<AccountView> {
    return value.map((x)=>from_candid_AccountView_n3(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NotificationView>): Array<NotificationView> {
    return value.map((x)=>from_candid_NotificationView_n10(_uploadFile, _downloadFile, x));
}
function to_candid_AccountType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AccountType): _AccountType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AccountType): {
    Savings: null;
} | {
    Checking: null;
} {
    return value == AccountType.Savings ? {
        Savings: null
    } : value == AccountType.Checking ? {
        Checking: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
